src/ESFA.DC.LARS.Web/Controllers/StandardDetailController.cs
using System.Threading.Tasks;
using ESFA.DC.LARS.Web.Interfaces.Services;
using ESFA.DC.LARS.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ESFA.DC.LARS.Web.Controllers
{
    [Route("StandardDetails")]
    public class StandardDetailController : Controller
    {
        private readonly IStandardApiService _standardApiService;

        public StandardDetailController(IStandardApiService standardApiService)
        {
            _standardApiService = standardApiService;
        }

        [Route("{standardCode}")]
        public async Task<IActionResult> Index(string standardCode)
        {
            var standard = await _standardApiService.GetStandard(standardCode);

            var model = new StandardDetailViewModel
            {
                Standard = standard
            };

            return View(model);
        }
    }
}

src/ESFA.DC.LARS.Web/Controllers/StandardLearningAimController.cs
using System.Threading.Tasks;
using ESFA.DC.LARS.Web.Interfaces.Services;
using ESFA.DC.LARS.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace ESFA.DC.LARS.Web.Controllers
{
    [Route("StandardLearningAims")]
    public class StandardLearningAimController : Controller
    {
        private readonly IStandardApiService _standardApiService;

        public StandardLearningAimController(IStandardApiService standardApiService)
        {
            _standardApiService = standardApiService;
        }

        [Route("{standardCode}")]
        public async Task<IActionResult> Index(string standardCode)
        {
            var standard = await _standardApiService.GetStandard(standardCode);

            var model = new StandardLearningAimsViewModel
            {
                Standard = standard
            };

            return View(model);
        }
    }
}

src/ESFA.DC.LARS.Web/Views/StandardDetail/Index.cshtml
@model ESFA.DC.LARS.Web.Models.ViewModels.StandardDetailViewModel
@{
    ViewData["Title"] = Model.Standard.StandardName;
}

@await Html.PartialAsync("_breadcrumbs")

<div class="govuk-grid-row">
    <div class="govuk-grid-column-two-thirds">
        <h1 class="govuk-heading-xl">
            @Model.Standard.StandardName
        </h1>
        <table id="high-level-info" class="govuk-table">
            <tbody class="govuk-table__body">
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Code</th>
                    <td class="govuk-table__cell">@Model.Standard.StandardCode</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Sector</th>
                    <td class="govuk-table__cell">@Model.Standard.StandardSectorCode - @Model.Standard.StandardSectorCodeDesc2</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Effective from</th>
                    <td class="govuk-table__cell">@Model.Standard.EffectiveFrom?.ToDateString()</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Effective to</th>
                    <td class="govuk-table__cell">@Model.Standard.EffectiveTo?.ToDateString()</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Last date for new starts</th>
                    <td class="govuk-table__cell">@Model.Standard.LastDateStarts?.ToDateString()</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Level</th>
                    <td class="govuk-table__cell">@Model.Standard.NotionalEndLevel</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Sector subject area</th>
                    <td class="govuk-table__cell">@Model.Standard.SectorSubjectAreaTier1 - @Model.Standard.SectorSubjectAreaTier1Desc</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Sector subject area Tier 2</th>
                    <td class="govuk-table__cell">@Model.Standard.SectorSubjectAreaTier2 - @Model.Standard.SectorSubjectAreaTier2Desc</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Integrated degree standard</th>
                    <td class="govuk-table__cell">@Model.Standard.IntegratedDegreeStandard</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Other body approval required</th>
                    <td class="govuk-table__cell">@Model.Standard.OtherBodyApprovalRequired</td>
                </tr>
            </tbody>
        </table>

        <ul class="govuk-list">
            <li render-if="Model.Standard.CommonComponents?.Count > 0">
                <a asp-action="Index" asp-controller="StandardCommonComponent" asp-route-standardCode="@Model.Standard.StandardCode"
                   class="govuk-link govuk-link--no-visited-state govuk-!-font-weight-bold no-underline govuk-!-font-size-19">Common components</a>
            </li>

            <li render-if="Model.Standard.LearningAims?.Count > 0">
                <a asp-action="Index" asp-controller="StandardLearningAim" asp-route-standardCode="@Model.Standard.StandardCode"
                   class="govuk-link govuk-link--no-visited-state govuk-!-font-weight-bold no-underline govuk-!-font-size-19">Related learning aims</a>
            </li>
        </ul>

        <h2 class="govuk-heading-l">Standard trailblazer</h2>
        <table id="high-level-info" class="govuk-table">
            <tbody class="govuk-table__body">
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Start date</th>
                    <td class="govuk-table__cell">@Model.Standard.EffectiveFrom?.ToDateString()</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">Last date for new starts</th>
                    <td class="govuk-table__cell">@Model.Standard.LastDateStarts?.ToDateString()</td>
                </tr>
                <tr class="govuk-table__row">
                    <th scope="row" class="govuk-table__header">End date</th>
                    <td class="govuk-table__cell">@Model.Standard.EffectiveTo?.ToDateString()</td>
                </tr>
            </tbody>
        </table>

        <partial name="_StandardFundingModel" model="Model" />
    </div>
</div>

@section PageScripts
{
    <script>
        var viewService = new ESFA.ViewService();
        viewService.setupStandardDetailsView("@Model.Standard.StandardCode", "@Model.Standard.StandardName");
    </script>
}